package utils

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Shell identifies a supported shell dialect for `kxd init` / `kxd shellenv`.
type Shell string

const (
	Bash       Shell = "bash"
	Zsh        Shell = "zsh"
	Fish       Shell = "fish"
	PowerShell Shell = "powershell"
)

// SupportedShells is the canonical list, in help/doc order.
var SupportedShells = []string{"bash", "zsh", "fish", "powershell"}

// AcceptedShells is everything ParseShell takes, including aliases. Used for
// argument validation and completion.
var AcceptedShells = append(append([]string{}, SupportedShells...), "pwsh")

// ParseShell maps a user-supplied shell name to a Shell.
func ParseShell(name string) (Shell, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "bash":
		return Bash, nil
	case "zsh":
		return Zsh, nil
	case "fish":
		return Fish, nil
	case "powershell", "pwsh":
		return PowerShell, nil
	}
	return "", fmt.Errorf("unsupported shell %q (supported: %s)", name, strings.Join(SupportedShells, ", "))
}

// ReadState returns the raw contents of ~/.kxd: the selected kubeconfig
// filename, or "" meaning KUBECONFIG should be unset. A missing file reads as
// empty rather than an error, so a fresh install still produces valid output.
func ReadState(loc string) (string, error) {
	data, err := os.ReadFile(filepath.Join(loc, ".kxd"))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

// quote wraps a value in single quotes, escaped for the given shell. Kubeconfig
// filenames come off the filesystem, so they can contain spaces and quotes.
func quote(sh Shell, value string) string {
	switch sh {
	case Fish:
		// Inside fish single quotes only \ and ' are special.
		r := strings.NewReplacer(`\`, `\\`, `'`, `\'`)
		return "'" + r.Replace(value) + "'"
	case PowerShell:
		// Inside PowerShell single quotes only ' is special, doubled to escape.
		return "'" + strings.ReplaceAll(value, "'", "''") + "'"
	default:
		// POSIX: end the quoted run, emit an escaped quote, reopen.
		return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
	}
}

// ShellEnv renders the KUBECONFIG mutation for the given ~/.kxd value as shell
// code, ready to be eval'd by the function that `kxd init` generates. This is
// the only place the ~/.kxd contract becomes an env change; the wrapper scripts
// used to duplicate it per shell, including the ~/.kube path join.
//
//   - empty value -> unset KUBECONFIG
//   - "config"    -> the default ~/.kube/config
//   - anything else -> ~/.kube/<value>
func ShellEnv(config, homeDir string, sh Shell) string {
	if config == "" {
		switch sh {
		case Fish:
			return "set -e KUBECONFIG\n"
		case PowerShell:
			return "$env:KUBECONFIG = $null\n"
		default:
			return "unset KUBECONFIG\n"
		}
	}

	path := filepath.Join(homeDir, ".kube", config)
	switch sh {
	case Fish:
		return fmt.Sprintf("set -gx KUBECONFIG %s\n", quote(sh, path))
	case PowerShell:
		return fmt.Sprintf("$env:KUBECONFIG = %s\n", quote(sh, path))
	default:
		return fmt.Sprintf("export KUBECONFIG=%s\n", quote(sh, path))
	}
}

// InitScript returns the shell integration to be eval'd from a shell rc file.
// It defines the kxd function, wires up completion, and applies the selection
// already in ~/.kxd so a new shell starts on the right kubeconfig.
func InitScript(sh Shell) string {
	switch sh {
	case Bash:
		return posixInit(Bash, "")
	case Zsh:
		return posixInit(Zsh, zshCompinit)
	case Fish:
		return fishInit
	case PowerShell:
		return powershellInit
	}
	return ""
}

// zsh needs bashcompinit to get the bash-style `complete` builtin, and
// bashcompinit needs compinit to have run first for compdef to exist. Most
// setups (oh-my-zsh and friends) have already run it, so only pay for it here
// if nothing else did.
const zshCompinit = `if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit
fi
autoload -U +X bashcompinit && bashcompinit
`

// posixInit covers bash and zsh, which differ only in needing bashcompinit to
// provide the bash-style `complete` builtin.
func posixInit(sh Shell, compinit string) string {
	return fmt.Sprintf(posixInitTemplate, string(sh), compinit)
}

// Namespace completion is deliberately absent everywhere: `kxd namespace list`
// calls the live cluster, and hanging the shell for up to 10s on a TAB press is
// worse than no completion.
const posixInitTemplate = `# kxd shell integration (%[1]s). Generated by: kxd init %[1]s
# Add to your rc file with: eval "$(kxd init %[1]s)"

kxd() {
  command kxd "$@" || return
  eval "$(command kxd shellenv %[1]s)"
}

_kxd_completion() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}
  local subcmd=${COMP_WORDS[1]}
  local suggestions

  case "$COMP_CWORD" in
    1)
      suggestions="$(command kxd file list) file context namespace"
      ;;
    2)
      case "$subcmd" in
        f|file|ctx|context|ns|namespace) suggestions="switch current list" ;;
        *)                               suggestions="" ;;
      esac
      ;;
    3)
      case "$prev" in
        s|switch)
          case "$subcmd" in
            f|file)      suggestions="$(command kxd file list)" ;;
            ctx|context) suggestions="$(command kxd context list)" ;;
            *)           suggestions="" ;;
          esac
          ;;
        *) suggestions="" ;;
      esac
      ;;
    *)
      suggestions=""
      ;;
  esac

  COMPREPLY=($(compgen -W "$suggestions" -- "$cur"))
  return 0
}

%[2]scomplete -o nospace -F _kxd_completion kxd

# Apply the kubeconfig already selected in ~/.kxd to this shell.
eval "$(command kxd shellenv %[1]s)"
`

const fishInit = `# kxd shell integration (fish). Generated by: kxd init fish
# Add to ~/.config/fish/config.fish with: kxd init fish | source

function kxd
    command kxd $argv; or return
    command kxd shellenv fish | source
end

complete -c kxd -f
complete -c kxd -n __fish_use_subcommand -a '(command kxd file list)'
complete -c kxd -n __fish_use_subcommand -a 'file context namespace'
complete -c kxd -n '__fish_seen_subcommand_from f file ctx context ns namespace' -a 'switch current list'
complete -c kxd -n '__fish_seen_subcommand_from f file; and __fish_seen_subcommand_from s switch' -a '(command kxd file list)'
complete -c kxd -n '__fish_seen_subcommand_from ctx context; and __fish_seen_subcommand_from s switch' -a '(command kxd context list)'

# Apply the kubeconfig already selected in ~/.kxd to this shell.
command kxd shellenv fish | source
`

const powershellInit = `# kxd shell integration (PowerShell). Generated by: kxd init powershell
# Add to your $PROFILE with: kxd init powershell | Out-String | Invoke-Expression

# Resolve the binary once, before the function below shadows the name. Unlike
# POSIX "command", PowerShell's & operator does not skip functions, so calling
# "& kxd" inside function kxd would recurse forever.
$global:KxdBin = (Get-Command -CommandType Application kxd -ErrorAction SilentlyContinue |
    Select-Object -First 1).Source
if (-not $global:KxdBin) {
    Write-Error "kxd: could not find the kxd binary on PATH"
    return
}

function kxd {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $Arguments)
    & $global:KxdBin @Arguments
    if ($LASTEXITCODE -ne 0) { return }
    & $global:KxdBin shellenv powershell | Out-String | Invoke-Expression
}

Register-ArgumentCompleter -CommandName kxd -ParameterName Arguments -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

    $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
    if ($wordToComplete) { $words = @($words | Select-Object -SkipLast 1) }

    $suggestions = @()
    if ($words.Count -eq 0) {
        $suggestions = @(& $global:KxdBin file list) + @('file', 'context', 'namespace')
    } elseif ($words.Count -eq 1) {
        if ($words[0] -in @('f', 'file', 'ctx', 'context', 'ns', 'namespace')) {
            $suggestions = @('switch', 'current', 'list')
        }
    } elseif ($words.Count -eq 2 -and $words[1] -in @('s', 'switch')) {
        if ($words[0] -in @('f', 'file')) { $suggestions = @(& $global:KxdBin file list) }
        elseif ($words[0] -in @('ctx', 'context')) { $suggestions = @(& $global:KxdBin context list) }
    }

    $suggestions | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}

# Apply the kubeconfig already selected in ~/.kxd to this shell.
& $global:KxdBin shellenv powershell | Out-String | Invoke-Expression
`
