#!/usr/bin/env bash

display_help() {
  echo "Usage: kxd [OPERATION]"
  echo " no operation    Switch configs."
  echo "  -c             Switch contexts."
  echo "  -h             Help. Displays this message."
  echo "  -v             Displays version"
}

display_version() {
  _kxd_prompt version
  return
}

run_context() {
  _kxd_prompt context
  return
}

run_main() {
  KUBECONFIG="$KUBECONFIG" _kxd_prompt
  selected_config="$(cat ~/.kxd)"

  if [ -z "$selected_config" ]
  then
    unset KUBECONFIG
  else
    export KUBECONFIG="$HOME/.kube/$selected_config"
  fi
}

arg=$(echo "$1" | tr '[:upper:]' '[:lower:]')

case "$arg" in
  -v|--v|version)
    display_version
    ;;
  -c|--c|context)
    run_context
    ;;
  -h|--h|help)
    display_help
    ;;
  *)
    run_main
    ;;
esac
