#!/usr/bin/env bash

if [[ "$1" == "version" ]]; then
  _kxd_prompt version
  return
fi

KUBECONFIG="$KUBECONFIG" _kxd_prompt

selected_config="$(cat ~/.kxd)"

if [ -z "$selected_config" ]
then
  unset KUBECONFIG
else
  export KUBECONFIG="$HOME/.kube/$selected_config"
fi
