#!/usr/bin/env bash

run_context() {
  _kxd_prompt --context
  return
}

run_list_context() {
  _kxd_prompt --list-context
  return
}

run_list_config() {
  _kxd_prompt --list
  return
}

display_help() {
  _kxd_prompt --help
  return
}

display_version() {
  _kxd_prompt --version
  return
}

run_main() {
  KUBECONFIG="$KUBECONFIG" _kxd_prompt
  selected_config="$(cat ~/.kxd)"

  if [ -z "$selected_config" ]
  then
    unset KUBECONFIG
  else
    export KUBECONFIG="$HOME/.kube/$selected_config"
  fi
}

arg=$(echo "$1" | tr '[:upper:]' '[:lower:]')

case "$arg" in
  -c|--context)
    run_context
    ;;
  -l|--list)
    run_list_config
    ;;
  -x|--list-context)
    run_list_context
    ;;
  -h|--help)
    display_help
    ;;
  -s|--switch)
    run_main
    ;;
  -v|--version)
    display_version
    ;;
  *)
    run_main
    ;;
esac
